import { Course, College, Scholarship, Government } from '../models/Education.js';
import { logger } from './logger.js';

const courses = [
  { title: 'B.Tech Computer Science', slug: 'btech-cs', description: '4-year engineering program in CSE.', shortDescription: 'Engineering degree in CS', category: 'engineering', type: 'degree', duration: { value: 4, unit: 'years' }, fee: { min: 50000, max: 200000 }, eligibility: '12th with PCM', streams: ['Science'], skills: ['Programming', 'Data Structures'], isDemo: true },
  { title: 'BCA', slug: 'bca', description: '3-year Bachelor of Computer Applications.', shortDescription: 'Undergraduate in computer apps', category: 'engineering', type: 'degree', duration: { value: 3, unit: 'years' }, fee: { min: 30000, max: 150000 }, eligibility: '12th any stream', streams: ['Science', 'Commerce'], skills: ['Programming', 'Web Dev'], isDemo: true },
  { title: 'MBBS', slug: 'mbbs', description: '5.5-year medical degree.', shortDescription: 'Medical degree', category: 'medical', type: 'degree', duration: { value: 5.5, unit: 'years' }, fee: { min: 10000, max: 1500000 }, eligibility: '12th with PCB, NEET', streams: ['Science'], skills: ['Biology', 'Chemistry'], isDemo: true },
  { title: 'BBA', slug: 'bba', description: '3-year business administration degree.', shortDescription: 'Business management degree', category: 'management', type: 'degree', duration: { value: 3, unit: 'years' }, fee: { min: 30000, max: 300000 }, eligibility: '12th any stream', streams: ['Commerce', 'Arts'], skills: ['Business', 'Management'], isDemo: true },
  { title: 'Diploma CE', slug: 'diploma-ce', description: '3-year diploma in Computer Engineering.', shortDescription: 'Diploma in computer engg', category: 'diploma', type: 'diploma', duration: { value: 3, unit: 'years' }, fee: { min: 10000, max: 50000 }, eligibility: '10th pass', streams: ['Science'], skills: ['Programming', 'Hardware'], isDemo: true },
  { title: 'Google Data Analytics', slug: 'google-data-analytics', description: 'Professional certificate by Google.', shortDescription: 'Data analytics certification', category: 'certification', type: 'certificate', duration: { value: 6, unit: 'months' }, fee: { min: 0, max: 5000 }, eligibility: 'Anyone', streams: ['Any'], skills: ['Data Analysis', 'SQL'], isOnline: true, certificationAvailable: true, isDemo: true },
  { title: 'AWS Cloud Practitioner', slug: 'aws-cloud', description: 'Cloud computing certification by AWS.', shortDescription: 'Cloud certification', category: 'certification', type: 'certificate', duration: { value: 3, unit: 'months' }, fee: { min: 5000, max: 15000 }, eligibility: 'Anyone', streams: ['Any'], skills: ['Cloud', 'AWS'], isOnline: true, certificationAvailable: true, isDemo: true },
  { title: 'MBA Marketing', slug: 'mba-marketing', description: '2-year MBA in Marketing.', shortDescription: 'Postgraduate business degree', category: 'management', type: 'degree', duration: { value: 2, unit: 'years' }, fee: { min: 100000, max: 2500000 }, eligibility: 'Graduation + CAT', streams: ['Commerce', 'Science'], skills: ['Marketing', 'Strategy'], isDemo: true },
  { title: 'ITI Electrician', slug: 'iti-electrician', description: '2-year ITI trade course.', shortDescription: 'Vocational training', category: 'iti', type: 'vocational', duration: { value: 2, unit: 'years' }, fee: { min: 5000, max: 20000 }, eligibility: '10th pass', streams: ['Science'], skills: ['Electrical'], isDemo: true },
  { title: 'Polytechnic ME', slug: 'poly-mech', description: '3-year diploma in Mechanical Engineering.', shortDescription: 'Polytechnic diploma', category: 'polytechnic', type: 'diploma', duration: { value: 3, unit: 'years' }, fee: { min: 10000, max: 40000 }, eligibility: '10th pass', streams: ['Science'], skills: ['Mechanical', 'CAD'], isDemo: true },
];

const colleges = [
  { name: 'IIT Bombay', slug: 'iit-bombay', description: 'Premier engineering institute.', shortDescription: 'Top engineering institute', type: 'university', ownership: 'government', location: { city: 'Mumbai', state: 'Maharashtra' }, courses: ['B.Tech', 'M.Tech'], streams: ['Engineering'], facilities: { hostel: true, library: true, lab: true }, fee: { min: 200000, max: 500000 }, rating: 4.8, established: 1958, isDemo: true },
  { name: 'Delhi University', slug: 'delhi-university', description: 'Central university.', shortDescription: 'Major central university', type: 'university', ownership: 'government', location: { city: 'Delhi', state: 'Delhi' }, courses: ['BA', 'BSc', 'BCA'], streams: ['Arts', 'Science'], facilities: { hostel: true, library: true }, fee: { min: 10000, max: 100000 }, rating: 4.5, established: 1922, isDemo: true },
  { name: 'Govt Polytechnic Mumbai', slug: 'govt-poly-mumbai', description: 'Government polytechnic.', shortDescription: 'Govt polytechnic college', type: 'polytechnic', ownership: 'government', location: { city: 'Mumbai', state: 'Maharashtra' }, courses: ['Diploma CE', 'Diploma ME'], streams: ['Engineering'], facilities: { lab: true, library: true }, fee: { min: 5000, max: 20000 }, rating: 4.0, established: 1960, isDemo: true },
  { name: 'Govt ITI Mumbai', slug: 'govt-iti-mumbai', description: 'Industrial training institute.', shortDescription: 'Vocational training institute', type: 'iti', ownership: 'government', location: { city: 'Mumbai', state: 'Maharashtra' }, courses: ['Electrician', 'Fitter'], streams: ['Vocational'], facilities: { lab: true }, fee: { min: 2000, max: 10000 }, rating: 3.8, established: 1950, isDemo: true },
];

const scholarships = [
  { name: 'NMMSS', slug: 'nmmss', description: 'Merit scholarship for weaker sections.', shortDescription: 'Merit scholarship', provider: 'Ministry of Education', type: 'merit', amount: { min: 12000, max: 12000 }, eligibility: { educationLevel: ['9th', '10th', '11th', '12th'], minPercentage: 55 }, deadline: new Date('2026-10-31'), sourceUrl: 'https://scholarships.gov.in', isGovernment: true, verificationStatus: 'verified', lastVerified: new Date(), isDemo: true },
  { name: 'AICTE Pragati', slug: 'aicte-pragati', description: 'Scholarship for girls in tech.', shortDescription: 'Women in tech scholarship', provider: 'AICTE', type: 'merit', amount: { min: 50000, max: 50000 }, eligibility: { educationLevel: ['undergraduate'], gender: 'female' }, deadline: new Date('2026-11-15'), sourceUrl: 'https://www.aicte-india.org', isGovernment: true, verificationStatus: 'verified', lastVerified: new Date(), isDemo: true },
  { name: 'PM Post Matric SC/ST', slug: 'pm-sc-st', description: 'Scholarship for SC/ST students.', shortDescription: 'SC/ST scholarship', provider: 'Ministry of Social Justice', type: 'need_based', amount: { min: 1000, max: 100000 }, eligibility: { educationLevel: ['12th', 'undergraduate'], caste: ['SC', 'ST'] }, deadline: new Date('2026-12-31'), sourceUrl: 'https://scholarships.gov.in', isGovernment: true, verificationStatus: 'verified', lastVerified: new Date(), isDemo: true },
  { name: 'NMAT GMAC', slug: 'nmat-gmac', description: 'Test fee waiver.', shortDescription: 'Test fee waiver', provider: 'GMAC', type: 'merit', amount: { min: 2000, max: 2000 }, eligibility: { educationLevel: ['undergraduate'] }, deadline: new Date('2026-09-30'), sourceUrl: 'https://www.nmat.com', isDemo: true, verificationStatus: 'unverified' },
];

const government = [
  { name: 'UPSC CSE', slug: 'upsc-cse', description: 'Civil services examination.', shortDescription: 'Premier civil services exam', category: 'exam', department: 'UPSC', eligibility: { educationLevel: ['undergraduate'], ageLimit: { min: 21, max: 32 } }, benefits: ['IAS', 'IPS', 'IFS'], deadline: new Date('2026-03-01'), sourceUrl: 'https://www.upsc.gov.in', location: 'All India', isDemo: true, verificationStatus: 'verified', lastVerified: new Date() },
  { name: 'SSC CGL', slug: 'ssc-cgl', description: 'Group B and C posts.', shortDescription: 'Govt recruitment exam', category: 'exam', department: 'SSC', eligibility: { educationLevel: ['undergraduate'], ageLimit: { min: 18, max: 32 } }, benefits: ['Central Govt jobs'], deadline: new Date('2026-04-15'), sourceUrl: 'https://ssc.nic.in', location: 'All India', isDemo: true, verificationStatus: 'verified', lastVerified: new Date() },
  { name: 'PMKVY', slug: 'pmkvy', description: 'Skill development scheme.', shortDescription: 'Free skill training', category: 'scheme', department: 'Ministry of Skill Dev', eligibility: { educationLevel: ['10th', '12th'], ageLimit: { min: 15, max: 45 } }, benefits: ['Free training', 'Certification'], sourceUrl: 'https://www.pmkvyofficial.org', location: 'All India', isDemo: true, verificationStatus: 'verified', lastVerified: new Date() },
  { name: 'Indian Navy SSR', slug: 'indian-navy-ssr', description: 'Navy recruitment for 12th pass.', shortDescription: 'Navy recruitment', category: 'job', department: 'Indian Navy', eligibility: { educationLevel: ['12th'], minPercentage: 50 }, benefits: ['Govt job', 'Salary', 'Pension'], deadline: new Date('2026-05-01'), sourceUrl: 'https://www.joinindiannavy.gov.in', location: 'All India', isDemo: true, verificationStatus: 'verified', lastVerified: new Date() },
];

export async function seedEducationData() {
  const [cCount, coCount, sCount, gCount] = await Promise.all([Course.countDocuments(), College.countDocuments(), Scholarship.countDocuments(), Government.countDocuments()]);
  if (cCount === 0) { await Course.insertMany(courses); logger.info(`Seeded ${courses.length} courses`); }
  if (coCount === 0) { await College.insertMany(colleges); logger.info(`Seeded ${colleges.length} colleges`); }
  if (sCount === 0) { await Scholarship.insertMany(scholarships); logger.info(`Seeded ${scholarships.length} scholarships`); }
  if (gCount === 0) { await Government.insertMany(government); logger.info(`Seeded ${government.length} government`); }
}
