import Career from '../models/Career.js';
import { logger } from './logger.js';

const careers = [
  { title: 'Software Engineer', slug: 'software-engineer', description: 'Design, develop, and maintain software applications.', shortDescription: 'Build software applications', category: 'technology', requiredSkills: [{ name: 'Programming', importance: 'essential' }, { name: 'Problem Solving', importance: 'essential' }], salaryRange: { entry: 400000, mid: 800000, senior: 1500000 }, demandLevel: 'high', growthOutlook: 'growing', pros: ['High salary', 'Remote work', 'Growing demand'], cons: ['Continuous learning', 'Tight deadlines'], workLifeBalance: 'good' },
  { title: 'Data Scientist', slug: 'data-scientist', description: 'Analyze complex data to help organizations make decisions.', shortDescription: 'Turn data into insights', category: 'technology', requiredSkills: [{ name: 'Python', importance: 'essential' }, { name: 'Statistics', importance: 'essential' }], salaryRange: { entry: 500000, mid: 1000000, senior: 2000000 }, demandLevel: 'high', growthOutlook: 'growing', pros: ['High demand', 'Good pay', 'Interesting work'], cons: ['Requires strong math', 'Data quality issues'], workLifeBalance: 'good' },
  { title: 'Doctor', slug: 'doctor', description: 'Diagnose and treat illnesses and injuries.', shortDescription: 'Healthcare professional', category: 'medical', requiredSkills: [{ name: 'Biology', importance: 'essential' }, { name: 'Empathy', importance: 'essential' }], salaryRange: { entry: 600000, mid: 1200000, senior: 2500000 }, demandLevel: 'high', growthOutlook: 'stable', pros: ['Respected profession', 'Job security', 'Helping others'], cons: ['Long education', 'Stressful', 'Long hours'], workLifeBalance: 'poor' },
  { title: 'Business Analyst', slug: 'business-analyst', description: 'Analyze business processes and recommend improvements.', shortDescription: 'Bridge business and tech', category: 'business', requiredSkills: [{ name: 'Analysis', importance: 'essential' }, { name: 'Communication', importance: 'essential' }], salaryRange: { entry: 400000, mid: 800000, senior: 1400000 }, demandLevel: 'medium', growthOutlook: 'stable', pros: ['Good pay', 'Varied work', 'Growth opportunities'], cons: ['Can be repetitive', 'Stakeholder management'], workLifeBalance: 'good' },
  { title: 'Civil Services Officer', slug: 'civil-services', description: 'Serve the government in administrative roles.', shortDescription: 'Government administration', category: 'government', requiredSkills: [{ name: 'General Knowledge', importance: 'essential' }, { name: 'Leadership', importance: 'essential' }], salaryRange: { entry: 500000, mid: 1000000, senior: 2000000 }, demandLevel: 'medium', growthOutlook: 'stable', pros: ['Job security', 'Power', 'Respect'], cons: ['Tough exam', 'Political pressure', 'Transfers'], workLifeBalance: 'moderate' },
  { title: 'Teacher', slug: 'teacher', description: 'Educate and inspire students.', shortDescription: 'Shape young minds', category: 'education', requiredSkills: [{ name: 'Communication', importance: 'essential' }, { name: 'Patience', importance: 'essential' }], salaryRange: { entry: 250000, mid: 500000, senior: 800000 }, demandLevel: 'medium', growthOutlook: 'stable', pros: ['Holidays', 'Job satisfaction', 'Shaping lives'], cons: ['Moderate pay', 'Administrative work'], workLifeBalance: 'excellent' },
  { title: 'Graphic Designer', slug: 'graphic-designer', description: 'Create visual content for brands and products.', shortDescription: 'Visual storytelling', category: 'creative', requiredSkills: [{ name: 'Creativity', importance: 'essential' }, { name: 'Adobe Tools', importance: 'essential' }], salaryRange: { entry: 250000, mid: 500000, senior: 900000 }, demandLevel: 'medium', growthOutlook: 'stable', pros: ['Creative freedom', 'Freelance options', 'Portfolio-based'], cons: ['Competitive', 'Client demands'], workLifeBalance: 'good' },
  { title: 'Agricultural Scientist', slug: 'agricultural-scientist', description: 'Research and improve agricultural practices.', shortDescription: 'Innovation in farming', category: 'agriculture', requiredSkills: [{ name: 'Biology', importance: 'essential' }, { name: 'Research', importance: 'essential' }], salaryRange: { entry: 350000, mid: 700000, senior: 1200000 }, demandLevel: 'medium', growthOutlook: 'stable', pros: ['Field work', 'Research', 'Social impact'], cons: ['Field conditions', 'Limited positions'], workLifeBalance: 'good' },
  { title: 'Digital Marketing Manager', slug: 'digital-marketing', description: 'Plan and execute online marketing strategies.', shortDescription: 'Online brand growth', category: 'business', requiredSkills: [{ name: 'Marketing', importance: 'essential' }, { name: 'Analytics', importance: 'essential' }], salaryRange: { entry: 350000, mid: 700000, senior: 1300000 }, demandLevel: 'high', growthOutlook: 'growing', pros: ['Dynamic work', 'Creative', 'Remote options'], cons: ['Fast-changing field', 'Pressure'], workLifeBalance: 'good' },
  { title: 'Mechanical Engineer', slug: 'mechanical-engineer', description: 'Design and build mechanical systems and machines.', shortDescription: 'Build machines and systems', category: 'engineering', requiredSkills: [{ name: 'Physics', importance: 'essential' }, { name: 'CAD', importance: 'essential' }], salaryRange: { entry: 350000, mid: 700000, senior: 1200000 }, demandLevel: 'medium', growthOutlook: 'stable', pros: ['Hands-on work', 'Diverse industries', 'Core engineering'], cons: ['Factory environments', 'Limited remote'], workLifeBalance: 'moderate' },
];

export async function seedCareers() {
  const count = await Career.countDocuments();
  if (count > 0) { logger.info(`Careers already seeded (${count})`); return; }
  await Career.insertMany(careers);
  logger.info(`Seeded ${careers.length} careers`);
}
